# Generated by Django 5.1 on 2024-08-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('likeCount', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pricePreview', models.CharField(max_length=50)),
                ('priceType', models.CharField(choices=[('fixed', 'FIXED'), ('negotiable', 'NEGOTIABLE')], max_length=20)),
                ('priceUnit', models.CharField(choices=[('unit', 'UNIT'), ('million', 'MILLION')], max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('published', 'PUBLISHED'), ('expired', 'EXPIRED')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('specs', models.JSONField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
